import "./globals.css";
import { Inter } from "next/font/google";
import favicon from "@/app/favicon.png";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Alejandro Morales | Portafolio Digital",
  description: "Generated by create next app",
  icons: {
    icon: `${favicon.src}`,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className="scroll-smooth" >
      <body className={inter.className}>{children}</body>
    </html>
  );
}
